version: '3.1'
services:
  appsrv:
    image: "golang:1.11.5-alpine"
    volumes:
      - .:/go/src/github.com/gvaduha/rainbgen
    working_dir: /go/src/github.com/gvaduha/rainbgen/cmd/rainbgen
    command: go run main.go
    ports:
      - ${SVCPORT}:${SVCPORT}
    depends_on:
      - "mongo"
    environment:
      SVCPORT: ${SVCPORT}
      MONGOCONNECTION: ${MONGOHOST}:${MONGOPORT}

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGOPORT}:${MONGOPORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGOGUIPORT}:${MONGOGUIPORT}
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
